version: '3'
services:
  nurseo:
    container_name: NurseO
    build:
      context: ./NurseO
      args:
        - NEXT_PUBLIC_basePath=${NEXT_PUBLIC_basePath}
        - NEXT_PUBLIC_domain=${NEXT_PUBLIC_domain}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - Google_CLIENT_ID=${Google_CLIENT_ID}
      - Google_CLIENT_SECRET=${Google_CLIENT_SECRET}
      - TEST_ENV=false
      - Demo_Mode=false
      - NEXT_PUBLIC_basePath=${NEXT_PUBLIC_basePath}
      - NEXT_PUBLIC_domain=${NEXT_PUBLIC_domain}
    volumes:
      - ./logo.png:/app/public/logo.png
    ports:
      - 3000:3000
      
  db:
    container_name: NurseO_DB
    image: mariadb:lts
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_DATABASE=NurseO
    volumes:
      - ./NurseO/prisma:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_HOST=db
      