version: '3'
services:
  nurseo: 
    container_name: NurseO
    build: 
      context: ./NurseO
      args:
        - NEXT_PUBLIC_basePath=${NEXT_PUBLIC_basePath}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - Google_CLIENT_ID=${Google_CLIENT_ID}
      - Google_CLIENT_SECRET=${Google_CLIENT_SECRET}
      - NEXT_PUBLIC_basePath=${NEXT_PUBLIC_basePath}
      - TEST_ENV=true
      - Demo_Mode=true
    volumes:
      - ./logo.png:/app/public/logo.png
    ports:
      - 3000:3000



