
INSERT INTO `Medication` (`id`, `brand_name`, `generic_name`, `narcoti_count_needed`) VALUES
(17, '', 'glucose tablet', 0),
(18, 'Celestone', 'betamethasone', 0),
(19, 'Tucks ', 'witch hazel external medicated pads', 0),
(20, 'Humulin R ', 'insulin regular', 0),
(21, 'D10 NS + 40 KCl', '10% dextrose in 0.9% sodium chloride with 40 mEq potassium chloride', 0),
(22, 'Ciprodex', 'Ciprofloxacin / Dexamethasone', 0),
(23, 'Lopressor', 'metoprolol', 0),
(24, '', '50% Dextrose', 0),
(25, 'Percocet', 'oxycodone and acetaminophen', 0),
(26, ' ', '5% dextrose in 0.9% sodium chloride', 0),
(27, '', 'prenatal vitamin', 0),
(28, '', 'morphine sulfate ', 0),
(29, '', 'multivitamin', 0),
(30, 'Augmentin', 'amoxicillin / clavulanate potassium ', 0),
(31, 'Buspar', 'buspirone', 0),
(32, '', '5% dextrose in 0.45% sodium chloride with 20 mEq potassium chloride', 0),
(33, 'Lantus', 'insulin glargine', 0),
(34, 'Bicitra', 'sodium citrate and citric acid', 0),
(35, 'Nitrostat', 'nitroglycerin', 0),
(36, 'Normal Saline', '0.9% sodium chloride', 0),
(37, '1/2 NS', '0.45% sodium chloride ', 0),
(38, 'Ortho Tri-Cyclen', 'ethinyl estradiol and norgestimate', 0),
(39, 'Dermoplast', 'benzocaine / menthol topical spray', 0),
(40, 'Narcan', 'naloxone HCL', 0),
(41, 'Zyprexa', 'olanzapine', 0),
(42, ' D5 1/2NS', '5% dextrose in 0.45% sodium chloride', 0),
(43, 'Motrin', 'ibuprofen', 0),
(44, 'Serevent Diskus', 'salmeterol', 0),
(45, '', '5% dextrose', 0),
(46, 'Pitocin', 'oxytocin', 0),
(47, 'Diastat ', 'diazepam', 0),
(48, 'Colace', 'docusate sodium', 0),
(49, '', '10% dextrose', 0),
(50, 'NPH', 'insulin isophane', 0),
(51, 'Reglan', 'metoclopramide', 0),
(52, ' Cogentin', 'benztropine', 0),
(53, '', 'Nitr Derm', 0),
(54, 'Prozac', 'fluoxetine', 0),
(55, 'Humalog', 'humalog insulin lispro', 0),
(56, 'Versed', 'midazolam', 0),
(57, 'Erythromycin', 'erythromycin base/sulfisoxazole', 0),
(58, '', 'sennosides-docusate sodium', 0),
(59, '', 'magnesium sulfate', 0),
(60, 'Rocephin', 'ceftriaxone', 0),
(61, 'Pepcid', 'famotidine', 0),
(62, '', 'albuterol sulfate', 0),
(63, 'Benadryl', 'diphenhydramine HCL', 0),
(64, '', 'melatonin', 0),
(65, 'Lasix', 'furosemide', 0),
(66, '', 'amoxicillin', 0),
(67, 'Lactated Ringers', 'LR', 0),
(68, 'Aspirin', 'acetylsalicylic acid', 0),
(69, 'Synthroid', 'levothyroxine', 0),
(70, 'Bicillin', 'penicillin G ', 0),
(71, 'Zofran', 'ondansetron', 0),
(72, 'Glucagen', 'glucagon', 0),
(73, 'NS + 40 KCl', '0.9% sodium chloride with 40 mEq potassium chloride', 0),
(74, 'Suboxone', 'buprenorphine', 0),
(75, 'Desyrel', 'trazodone', 0),
(76, 'K-Dur', 'potassium chloride', 0),
(77, 'Banana Bag', '100 mg Thiamine, 1 mg Folic Acid, Low Dose Multivitamin, 3 grams Magnesium Sulfate', 0),
(78, '', 'thiamine HCL', 0),
(79, '', 'sodium citrate', 0),
(80, 'Lovenox', 'enoxaparin', 0),
(81, 'Methergin', 'methylergonovine maleate', 0),
(82, 'Humulin R in Normal Saline ', 'insulin regular in 0.9% sodium chloride', 0),
(83, 'Coumadin', 'warfarin', 0),
(84, '', 'Calcium Gluconate', 0),
(85, 'Nubain', 'nalbuphine HCL', 0),
(86, 'Cytotec', 'misoprostol ', 0),
(87, 'Ativan', 'lorazepam', 0),
(88, 'Tylenol', 'acetaminophen', 0),
(89, 'Ancef', 'cefazolin', 0),
(90, 'Elavil', 'amitriptyline ', 0),
(91, 'Glucophage', 'Metformin', 0),
(92, 'Oxypro', 'Oxycodone', 0),
(94, 'Hemabate', 'carboprost tromethamine', 0),
(95, 'Lysteda', 'tranexamic acid', 0);
